# Generated by Django 3.2.4 on 2021-06-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataplot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='time',
        ),
        migrations.RemoveField(
            model_name='column',
            name='value',
        ),
    ]
