# Generated by Django 3.2.4 on 2021-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplot', '0002_auto_20210612_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
